export const CERTIFICATIONS = [
  {
    id: "redhat",
    name: "RedHat Certified Developer",
    issuer: "RedHat",
    year: "2024",
    description: "Certified as a Red Hat Certified Enterprise Application Developer",
    verificationUrl: "https://rhtapps.redhat.com/verify?certId=240-187-393",
    certId: "240-187-393",
    validUntil: "November 10, 2026",
  },
  {
    id: "aviatrix",
    name: "Aviatrix Multi Cloud",
    issuer: "Aviatrix",
    year: "2024",
    description: "Aviatrix Certified Engineer - Multicloud Network Associate",
    verificationUrl: "https://www.credly.com/badges/2518dfea-b7c4-4e39-a19e-ca649ee88537",
    certId: "2024-21870",
    validUntil: "September 10, 2027",
  },
  {
    id: "automation-anywhere",
    name: "Automation Anywhere Certification",
    issuer: "Automation Anywhere",
    year: "2024",
    description: "Automation Anywhere Certified Professional",
    verificationUrl: "https://certificates.automationanywhere.com/757fd6d1-ebd6-4bc8-9721-5505e69425a0#acc.dKB1eQYy",
    certId: "AAESSE2024A360 - 122113677",
    validUntil: "November 10, 2026",
  },
  {
    id: "salesforce",
    name: "Salesforce AI Associate",
    issuer: "Salesforce",
    year: "2024",
    description: "Salesforce Certified AI Associate",
    verificationUrl: "https://www.salesforce.com/trailblazer/dqv5hhxruerin9tsz4",
    certId: "Salesforce AI Associate",
    validUntil: "2026",
  },
]
